# Generated by Django 4.1 on 2023-11-17 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_tag_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя фильтра')),
            ],
            options={
                'verbose_name': 'Фильтры',
                'verbose_name_plural': 'Фильтры',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='filters',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Фильтр'),
        ),
    ]
