# Generated by Django 4.1 on 2023-11-25 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_filters_tag_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='filters',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='filters',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.filters', verbose_name='Фильтр'),
        ),
    ]
