# Generated by Django 5.0 on 2024-02-19 22:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_filters_slug_alter_tag_filters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('number', models.FloatField(verbose_name='Номер корпуса')),
                ('floors', models.IntegerField(validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)], verbose_name='Этажность')),
                ('available', models.BooleanField(default=True, verbose_name='Доступность')),
            ],
            options={
                'verbose_name': 'Корпусы',
                'verbose_name_plural': 'Корпусы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('description2', models.TextField(null=True, verbose_name='Описание')),
                ('available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('date', models.DateTimeField(verbose_name='Заселение до')),
            ],
            options={
                'verbose_name': 'Объекты',
                'verbose_name_plural': 'Объекты',
                'ordering': ('title',),
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='Площадь'),
        ),
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='product',
            name='floors',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)], verbose_name='Этажность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='frame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.frame', verbose_name='Корпус'),
        ),
        migrations.AddField(
            model_name='frame',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.object', verbose_name='Объект'),
        ),
    ]
