# Generated by Django 5.0 on 2024-02-19 23:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_frame_object_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('title',), 'verbose_name': 'Квартиры', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterField(
            model_name='product',
            name='area',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='Артикул'),
        ),
    ]
