# Generated by Django 5.0 on 2024-02-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_product_options_alter_product_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='ceiling_height',
            field=models.FloatField(null=True, verbose_name='Высота потолков'),
        ),
        migrations.AlterField(
            model_name='product',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Площадь'),
        ),
    ]
