# Generated by Django 5.0 on 2024-02-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_frame_ceiling_height_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchased',
            field=models.BooleanField(default=True, verbose_name='Доступность для покупки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступность для аренды'),
        ),
    ]
