# Generated by Django 5.0 on 2024-02-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_purchased_alter_product_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='purchased',
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступность'),
        ),
    ]
